---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  #always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012R2
   # driver_config:
    #  box: windows-2012R2-serverstandard-amd64_virtualbox.box
    transport:
      name: winrm
      elevated: true

suites:
  - name: default
    run_list:
      - recipe[ssms::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
